### ISSUE TITLE
Docs: Diátaxis refactor - iteration 0 high-level tracking

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9745]
In order to be able to work on subsequent iterations, we need to firstly add the following features to our documentation:

* [x] Existing doc PRs are merged or marked as blocked:
  * https://github.com/readthedocs/readthedocs.org/pull/9734
  * https://github.com/readthedocs/readthedocs.org/pull/9731
  * https://github.com/readthedocs/readthedocs.org/pull/9625
  * ~https://github.com/readthedocs/readthedocs.org/pull/7859~ blocked

* [x] In the proposed structure, Explanation mixes Business and Community features. This will require a simple DRY way of repeating the same “This feature is only available on Read the Docs for Business” kind of box. We could use a Sphinx replacement directive for this. https://github.com/readthedocs/readthedocs.org/pull/9754

* [x] Open a long-lived `diataxis/main` feature branch, which we may merge into `main` at the end of each iteration (or not)
* [x] Retarget existing PRs to `diataxis/main`
* [x] Establishing a basic layout for Explanation, How-To and Reference:
  * **Tutorials** replaces “First steps”
  * **Explanation** is added before “Features” & “Advanced Features”
  * **How-to** stays
  * **Reference** is added, moving the simplest existing references there immediately so it’s not empty
  * Read the Docs for Business and About Read the Docs simply stay put (Read the Docs for Business is dissolved in Iteration 1 and About Read the Docs is dissolved in Iteration 2)
  * https://github.com/readthedocs/readthedocs.org/pull/9758

**Comment by benjaoming** [comment]
@ericholscher I've added the last item just now

>  Open a long-lived diataxis feature branch, which we may merge into main at the end of each iteration (or not)

The idea was that we should have this branch up-front and add a public&hidden version for the branch.

**Comment by ericholscher** [comment]
Yep, agreed 👍

**Comment by benjaoming** [comment]
Looking at the last item now in the list (which changes the sidebar navigation), I think this will be a good "first step" to launch that branch and then rehearse how we will evaluate if it's going into main or not!

**Comment by benjaoming** [comment]
This is all done now and ready for Iteration 1 :tada:
