### ISSUE TITLE
Docs: Diátaxis refactor - iteration 1 high-level tracking

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9746]
Successor of #9745 

This is a high-level issue moved from the [initial planning document](https://docs.google.com/document/d/1LQXMUOAKBZ4RhAew2F4TCDp-QW7czH5Dq6BPxlyA_dw/edit#). Further issues may be opened and linked from here.

**Acceptance criteria:** All documentation content is correctly categorized in _Explanation_, _How-to_ and _Reference_, according to Diátaxis. This means moving pages, splitting up pages and writing new content. This also merges all _Business Features_ into _Explanation_ and _How-to_. Removes everything from _Features_ that isn't a feature, and combines _Features_ with _Advanced Features_.

**Outcome:** _Features_ is a list of old feature files without any purely Explanation/Reference/How-To left. _RTD for Business_ and _Advanced Features_ are gone from the sidebar. _About RTD_ is mostly untouched. To avoid scope creep, we are not changing sub-levels of How-to guides but keeping the old ones - new How-to guides can be added casually in those existing levels since it will change in the next iteration.

### Relabel
Existing contents are moved with light changes to title and content. Intentionally not called “move” because we don’t change URLs and break stuff, we just relabel it.

* [x] Relabel "Choosing Between Our Two Platforms" to Explanation https://github.com/readthedocs/readthedocs.org/pull/9784
* [x] Relabel "Subprojects" in Explanation (Title suggestion: "Combining many projects in one: Subprojects") https://github.com/readthedocs/readthedocs.org/pull/9785
* [x] Relabel "Localization of Documentation" in Explanation (Title suggestion: "Localization (Translation): Considerations and workflows") https://github.com/readthedocs/readthedocs.org/pull/9790
* [x] Relabel "Read the Docs for Science" in Explanation (Title suggestion: "Using documentation in Science and Academic Publishing") https://github.com/readthedocs/readthedocs.org/pull/9832
* [ ] Relabel "Build process" in Explanation (Title suggestion: "Build process overview") (@ericholscher)
  * Implement inputs from @agjohnson https://github.com/readthedocs/readthedocs.org/issues/9575
* [x] Relabel "Single Version Documentation" to Explanation (same title?) https://github.com/readthedocs/readthedocs.org/pull/9835
* [x] Relabel "Connecting Your VCS Account" in Explanation (Title suggestion: "Integration and authentication through git platforms") https://github.com/readthedocs/readthedocs.org/pull/9834
* [x] Relabel "Organizations" to Explanation (no new title suggested for now, but remember that it's a Business feature) https://github.com/readthedocs/readthedocs.org/pull/9836
* [x] Relabel "Automatic Redirects" to Explanation (no new title suggested for now, is this a member or business feature?) https://github.com/readthedocs/readthedocs.org/pull/9896
* [x] Relabel "Server Side Search" to Explanation / Fast Server Side Search. Most likely, https://github.com/readthedocs/readthedocs.org/pull/9625 is covering the remaining parts. https://github.com/readthedocs/readthedocs.org/pull/9897
* [x] Relabel "Technical Documentation Search Engine Optimization (SEO) Guide" from How-to Guides to Explanation https://github.com/readthedocs/readthedocs.org/pull/10004
* [x] Relabel "Connecting Your VCS Account" to "How to connect your user account with GitHub, GitLab and Bitbucket (and?)" in How-to https://github.com/readthedocs/readthedocs.org/pull/9834
* [x] Relabel "Frequently Asked Questions" to How-to (note that the section is intended to be converted into how-tos and ultimately deleted) https://github.com/readthedocs/readthedocs.org/pull/9908
* [x] Relabel "Build troubleshooting" to "Troubleshooting builds" in How-to https://github.com/readthedocs/readthedocs.org/pull/9914
* [x] Relabel "My Build is Using Too Many Resources" to "Troubleshooting slow builds" in How-to https://github.com/readthedocs/readthedocs.org/pull/9914
* [x] Relabel "Feature Flags" to Reference (candidate for later deletion, no worries here) https://github.com/readthedocs/readthedocs.org/pull/9915
* [x] Relabel "Policy for Abandoned Projects" to "Abandoned Projects Policy" and move to Reference https://github.com/readthedocs/readthedocs.org/pull/9916

### Split
Existing article is split up and some new contents are added to shape the new results. Every Split action has at least 2 destinations.

* [ ] Split "Flyout Menu"
  * Explanation / Anatomy of the Read the Docs “Flyout” Menu
  * How-to / How to customize Read the Docs “Flyout” Menu
    - Example: https://stackoverflow.com/questions/50425740/how-to-find-the-pdf-version-of-a-read-the-docs-project
* [x] Split "Status Badges" https://github.com/readthedocs/readthedocs.org/pull/9951
  * Explanation / Clearly indicate your efforts with a Status Badge
  * How-to / How to add a badge
* [ ] Split "Configuration File" https://github.com/readthedocs/readthedocs.org/pull/9921
  * Explanation / Configuration File: Using “Configuration as Code” (.readthedocs.yaml)
  * Reference / Configuration File
  * Bonus: Post an issue that we should perhaps have a How-to for adding a configuration file to a project?
* [ ] Split "Build customization"
  * Discussed on call: Let's focus on reference
  * Explanation / Build process details
  * How-to / How to override the entire default build process (Docsify, Pelican, Hugo and more)
  * It's possible that this will generate more how-to articles.
  * Implement inputs from @agjohnson https://github.com/readthedocs/readthedocs.org/issues/9575
* [x] Split "Environment Variables" https://github.com/readthedocs/readthedocs.org/pull/9966
  * Explanation / Build environments and secrets
  * Reference / Environment Variables
* [ ] Split "Reproducible Builds" (@ericholscher)
  * Explanation / Reproducible Builds
  * How-to / How to write a requirements.txt for Reproducible Builds
* [x] Split "Custom Domains"
  * Start from https://github.com/readthedocs/readthedocs.org/pull/9676
  * Explanation / Custom Domains
  * How-to / How to set a custom domain
* [x] Split "Downloadable Documentation"
  * Explanation / Offline Formats
  * How-to / How to generate PDF and ePub (Sphinx)
  * Rename to "offline formats" and close https://github.com/readthedocs/readthedocs.org/issues/9577
  * PR: https://github.com/readthedocs/readthedocs.org/pull/9768
* [x] Split "Documentation Hosting Features" https://github.com/readthedocs/readthedocs.org/pull/9952
  * Explanation / Serving content and built-in features
  * How-to / How to set a custom 404
  * How-to / How to create a custom robots.txt
  * There might be more how-tos that can be spun-off from existing explanation contents - open issues or write new how-tos?
* [x] Split "Canonical URLs"
  * Explanation / Canonical URLs: Effectively archiving old versions
  * How-to / How to use Canonical URLs
  * Work will happen in this PR: https://github.com/readthedocs/readthedocs.org/pull/9676
* [x] Split "Project Privacy Level" and "Secret links and password protected documentation" https://github.com/readthedocs/readthedocs.org/pull/10007
  * Explanation / Private projects
  * Explanation / Secret links and password protected documentation
  * How-to / How to make a project private and share it
* [ ] Split "Build Notifications and Webhooks"
  * Discussed on call: Let's focus on reference
  * Reference / features / Build Notifications and Webhooks
  * Reference / features / Preview Preview Documentation from Pull Requests
  * How-to / How to setup a Slack build notification
* [x] Split "VCS Integrations"
  * Start from https://github.com/readthedocs/readthedocs.org/pull/9675
  * Explanation / Connecting git repositories
  * How-to / How to connect your Git repository
* [x] Split "Preview Documentation from Pull Requests"
  * Explanation / Preview Documentation from Pull Requests
  * How-to / How to configure pull request builds
  * Start from https://github.com/readthedocs/readthedocs.org/pull/9679
  * Observe and implement inputs from https://github.com/readthedocs/readthedocs.org/issues/9574
* [x] Split "Single Sign-On"
  * Explanation / Single Sign-On for organizations
  * How-to / How to setup Single Sign-On (SSO) for your organization
  * PR: https://github.com/readthedocs/readthedocs.org/pull/9801
* [x] Split "Automation Rules" https://github.com/readthedocs/readthedocs.org/pull/9953
  * Explanation / Automation Rules
  * How-to / How to create new versions automatically
* [x] Split "User-defined Redirects" https://github.com/readthedocs/readthedocs.org/pull/9896
  * Explanation / User-defined Redirects
  * How-to / How to create redirect rules
* [x] Split "Traffic Analytics"
  * Start from https://github.com/readthedocs/readthedocs.org/pull/9677
  * Explanation / Traffic Analytics
  * How-to / How to enable and disable Google Analytics
  * How-to / How to understand your users’ interaction with your documentation (Just noting 
that this article is scoped for ITERATION 4!)
* [x] Split "Security Log" https://github.com/readthedocs/readthedocs.org/pull/9985
  * Explanation / Security Logging
  * How-to / How to enable and use Security Logs

### New
An entirely new article is created

* None

### Remove

* [x] Remove "Google Summer of Code" - "Don't need it in the menu. Perhaps mark it `:orphan:`, or just link it from some deprecated content page?" https://github.com/readthedocs/readthedocs.org/pull/9949

### Wrapping up

* [x] "Advanced Features" and "Read the Docs for Business" should be empty and removed. "Features" should also be empty and removed, but ff there are articles left here, we need to deal with them by adding new tasks/issues. Make note of "None" actions that simply place an article under Features without any further changes. https://github.com/readthedocs/readthedocs.org/pull/10010
  * Versioned Documentation

### Iteration 1.5 - "Put a bow on it" 

* Do an SEO audit on H1's of all pages
* Refactor the index page to highlight our fancy new docs
* Ship it on `latest` & `stable`!! 🎉

**Comment by ericholscher** [comment]
I'd like to see us moving faster here. A proposal to discuss in our call tomorrow:

* Benjamin to try to get 1 draft PR refactor up per day (checking off at least 1 item on the iteration)
* Eric to try to do a "v2" of an incoming draft PR each day. Basically do an edit & copy iteration instead of a bunch of GH comments, so things don't get blocked on review as long

Does that make sense to try out for a sprint and see if we can get a faster cadence going?
