### ISSUE TITLE
Docs: Diátaxis refactor - iteration 2 high-level tracking

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9747]
Successor of #9746 

This is a high-level issue moved from the [initial planning document](https://docs.google.com/document/d/1LQXMUOAKBZ4RhAew2F4TCDp-QW7czH5Dq6BPxlyA_dw/edit#). Further issues may be opened and linked from here.

* **Acceptance Criteria:** New sub-levels are created in Explanation and How-to, old How-to sub-levels are removed, Any remaining “Features” are moved to Reference and finally delete “Features”. Out of scope: Articles that have to be created from scratch.

* **Outcome:** The menu already starts to have clear entrypoints aligned with Diátaxis (but it is still lengthy).

### Ongoing work from iteration 1

* [x] Relabel "Build process" in Explanation (Title suggestion: "Build process overview") (@ericholscher)
  * Implement inputs from @agjohnson https://github.com/readthedocs/readthedocs.org/issues/9575
  * https://github.com/readthedocs/readthedocs.org/pull/10028
* [x] ~Split "Flyout Menu"~ We can skip this, a new flyout menu is on its way
  * Reference / Features / Flyout Menu - https://docs.readthedocs.io/en/stable/flyout-menu.html
  * How-to / How to customize Read the Docs “Flyout” Menu
    - Example: https://stackoverflow.com/questions/50425740/how-to-find-the-pdf-version-of-a-read-the-docs-project
* [x] Split "Configuration File" https://github.com/readthedocs/readthedocs.org/pull/10416
  * Explanation / Configuration File: Using “Configuration as Code” (.readthedocs.yaml)
  * Reference / Configuration File
  * Bonus: Post an issue that we should perhaps have a How-to for adding a configuration file to a project?
* [x] Split "Build customization" https://github.com/readthedocs/readthedocs.org/pull/10028
  * Discussed on call: Let's focus on reference
  * Explanation / Build process details
  * How-to / How to override the entire default build process (Docsify, Pelican, Hugo and more)
  * It's possible that this will generate more how-to articles.
  * Implement inputs from @agjohnson https://github.com/readthedocs/readthedocs.org/issues/9575
* [x] Split "Reproducible Builds" (@ericholscher) https://github.com/readthedocs/readthedocs.org/pull/10030
  * Explanation / Reproducible Builds
  * How-to / How to write a requirements.txt for Reproducible Builds
* [x] Split "Build Notifications and Webhooks" https://github.com/readthedocs/readthedocs.org/pull/10396
  * Discussed on call: Let's focus on reference
  * [x] Reference / features / Build Notifications and Webhooks
  * [x] Reference / features / Preview Preview Documentation from Pull Requests
  * [x] How-to / How to setup a [Slack,Discord] build notification
  * [x] ~Actual screenshots on build notifications~ No space, already plenty of illustrations here.

### Before everything else

About creating new sub-levels: A sub-level contains a stub index.rst with a TOC. The TOC can refer to any other page in the Sphinx project, but make sure to _remove_ that page from other TOCs.

* [x] Fix the mixup of Title Case and Sentence case. https://github.com/readthedocs/readthedocs.org/pull/10055
* [x] Create follow-up tasks from #10026 https://github.com/readthedocs/readthedocs.org/pull/10039
* [x] Updates to style guide around build terminology: Steps, jobs, commands etc. https://github.com/readthedocs/readthedocs.org/pull/10250
* [x] Updates to style guide for consistency around what to call the "Config File" https://github.com/readthedocs/readthedocs.org/pull/10250
* [x] Add all new sub-levels in **Explanation** https://github.com/readthedocs/readthedocs.org/pull/10071
  * See [initial planning document](https://docs.google.com/document/d/1LQXMUOAKBZ4RhAew2F4TCDp-QW7czH5Dq6BPxlyA_dw/edit#) for title suggestions
  * Write introductions and create a nice menu using description lists and emojis
* [x] Add all new sub-levels in **How-to guides** https://github.com/readthedocs/readthedocs.org/pull/10131
  * See [initial planning document](https://docs.google.com/document/d/1LQXMUOAKBZ4RhAew2F4TCDp-QW7czH5Dq6BPxlyA_dw/edit#) for title suggestions
  * Write introductions and create a nice menu using description lists and emojis
* [x] Add all new sub-levels in **Reference**
  * Resolve suggestion to also have a combined level Reference => API (containing Platform API and Search API)
  * Move all existing pages to their destination sub-level. Some pages do not have sub-levels. Do not rename anything. See [initial planning document](https://docs.google.com/document/d/1LQXMUOAKBZ4RhAew2F4TCDp-QW7czH5Dq6BPxlyA_dw/edit#).

### Glossary update

* [x] Add more common terms to the glossary and apply them where they are needed. Common words: "reproducible", "docs", "pinning" https://github.com/readthedocs/readthedocs.org/pull/10249
* [x] Ensure we're no longer saying "VCS" anywhere that can just read "Git".

### Relabel

Existing contents are moved with light changes to title and content. Intentionally not called “move” because we don’t change URLs and break stuff, we just relabel it.

* [x] We want to figure out a better sublevel title for "How-to / Content, themes and SEO"
* [x] Re: https://github.com/readthedocs/readthedocs.org/pull/10131#discussion_r1131702864
  * How-to / "Connecting an automatically imported Git repository" https://github.com/readthedocs/readthedocs.org/pull/10247
  * How-to / "Connecting a manually imported Git repository" https://github.com/readthedocs/readthedocs.org/pull/10247
  * Reuse warning from https://docs.readthedocs.io/en/latest/guides/importing-private-repositories.html on other

### Split
Existing article is split up and some new contents are added to shape the new results. Every Split action has at least 2 destinations.

* _Empty_

### Improve

* [x] Needs some general updating: https://docs.readthedocs.io/en/latest/guides/importing-private-repositories.html https://github.com/readthedocs/readthedocs.org/pull/10251
* [x] Main index page rough update https://github.com/readthedocs/readthedocs.org/pull/10186
* [x] Research solutions and enablers for page meta data https://github.com/readthedocs/readthedocs.org/issues/10157
* [x] Open issue with discussion around the next iteration on the main index page https://github.com/readthedocs/readthedocs.org/issues/10252

### New

* [ ] New article from "Choosing between our two platforms", title draft: "Choosing a dedicated documentation platform". https://github.com/readthedocs/readthedocs.org/pull/10071
* [x] Feature page about Git Integration https://github.com/readthedocs/readthedocs.org/pull/10442

### Remove

* [x] Remove "Read the Docs for Business" - analyze if certain contents might live elsewhere.

### After everything else

* [x] "All How-to Guides - Index page" is created as the last sub-level in How-to Guides.
* [x] old How-to sub-levels are removed, Any remaining “Features” are moved to Reference and finally delete “Features”
* [x] ~About Read the Docs is removed (if it wasn't already removed)~ It doesn't make sense to remove right now

**Comment by benjaoming** [comment]
Dumping some notes from the sentence-case refactor... will order them as tasks later in this or other iterations... or not at all:

* We should use refactor our docs to use `menuselection` in a lot of cases where we use `guilabel`.
* A lot of places could benefit from `tabs::` to show alternative instructions for GitHub/Bitbucket or Sphinx/MkDocs etc.
* We write our features with lower-case generally. For instance "server side search" is a feature, but it's not a Proper Noun. We haven't named features as such.

**Comment by benjaoming** [comment]
A lot of guides have Troubleshooting nested inside the guide, while some other troubleshooting items are separate. I'm wondering if this should be changed so all Troubleshooting is lodged next to its how-to guide, rather than in separate sections.

**Comment by ericholscher** [comment]
> We should generally write "documentation" rather than "docs".

Kinda goes against our brand, though? Not sold on this one.

> Sphinx-specific guides should use a convention: "How to do X (Sphinx)"

I think you just want `in Sphinx`. Using any other convention feels weird to a reader or Googler. 

> We should use refactor our docs to use menuselection in a lot of cases where we use guilabel.

Seems quite low priority, FWIW. Only if we do another full doc review, or just in the normal work of updating content.

> "Read the Docs for Community" => "Read the Docs Community" (or just use org_brand)

Yea, I thought that's what we were doing already? 

> "Configuration file" not "Configuration File" or "Config File".

Again, I'm not 100% sold that the longer version is better here. Config is pretty commonly used, but worth a discussion. 

> A lot of guides have Troubleshooting nested inside the guide, while some other troubleshooting items are separate. I'm wondering if this should be changed so all Troubleshooting is lodged next to its how-to guide, rather than in separate sections.

This seems reasonable for small troubleshooting suggestions. Breaking them out is almost certainly going to make a worse experience for the user.

**Comment by benjaoming** [comment]
* Found an occurrence in config file v2 "Our build servers run Ubuntu 18.04, with the default set of package repositories installed. We don't currently support PPA's or other custom repositories."

**Comment by agjohnson** [comment]
>> We should generally write "documentation" rather than "docs".
> Kinda goes against our brand, though? Not sold on this one.

I'm +1 on `documentation` generally, `docs` is a bit jargony or at least shorthand, and it has overlap with "docs" authored from Word/Google Docs/etc or "legal docs".

**Comment by ericholscher** [comment]
> > > We should generally write "documentation" rather than "docs".
> > 
> > 
> > Kinda goes against our brand, though? Not sold on this one.
> 
> I'm +1 on `documentation` generally, `docs` is a bit jargony or at least shorthand, and it has overlap with "docs" authored from Word/Google Docs/etc or "legal docs".

Good point. Makes sense for a general rule to use `documentation` I guess.

**Comment by benjaoming** [comment]
Note to add something in our style guide about using explicit labels rather than headlines, the refactor shows that it's harder to improve headlines when they are also used in references that break. We probably want to tweak more headlines.

**Comment by ericholscher** [comment]
Going to call this done, as we've finished up the last little bits here. :tada:
