### ISSUE TITLE
 Docs: Diátaxis refactor - iteration 3 high-level tracking

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9748]
Successor of #9747

This is a high-level issue moved from the [initial planning document](https://docs.google.com/document/d/1LQXMUOAKBZ4RhAew2F4TCDp-QW7czH5Dq6BPxlyA_dw/edit#). Further issues may be opened and linked from here.

* **Acceptance criteria:** New & high priority content is added. Trims out a couple of articles that aren’t trivial to remove.

* **Outcome:** Navigation is shortened a bit, new articles added directly in their destination sub-levels.

### Relabel

* [ ] **Reference / Site Support** becomes "Tutorials / How to get help" ?

#### Split and remove

* [ ] **How-to Guides / Troubleshooting / Frequently Asked Questions** is possibly divided into new how-to guides or it's simply removed.

### New and content changes

* [ ] We should have an extra look at how we deal with Configuration files and label their version: https://github.com/readthedocs/readthedocs.org/issues/8648
* [ ] Versioned Documentation: https://github.com/readthedocs/readthedocs.org/issues/9572
* [ ] Write an article about "integrated search", i.e. the ability to search across your own or your organization's documentation projects. See https://readthedocs.slack.com/archives/GHNRFLPNJ/p1676387562016269

### Remove

* [ ] Remove "Main Features" (it might live in Reference or Explanation, depending on decision from previous iteration)
* [ ] **Reference / Feature Flags** is removed or orphaned

**Comment by ericholscher** [comment]
I think we're not tracking this work anymore and it's gone stale. Going to close the tracking issues.
