### ISSUE TITLE
 Docs: Diátaxis refactor - iteration 4 high-level tracking

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9749]
Successor of #9748 

This is a high-level issue moved from the [initial planning document](https://docs.google.com/document/d/1LQXMUOAKBZ4RhAew2F4TCDp-QW7czH5Dq6BPxlyA_dw/edit#). Further issues may be opened and linked from here.

* **Acceptance criteria:** Documentation no longer has anything that makes it possible to tell that it’s undergoing a restructure.

* **Outcome:** Brushing off all the rough corners, adding new index pages for Explanation and How-to content, new “All Features” index page (potentially adding features via [data ](https://sphinxcontribdatatemplates.readthedocs.io/en/latest/)templates), small tweaks to the main index page to match the new structure.

### New

* [ ] We might want a page like "Setting up a local authoring environment and investigating errors" to exist in Tutorials. There is some tension around the length of the sidebar, so might investigate adding a major sub-level "Getting started" or "Creating your first project" vs. "Adding an existing project" etc.
* [ ] Suggestion to add "Working with themes and branding" in **Explanation / Writing Documentation**
* [ ] "Custom 404s" added in **Explanation / Publishing: How documentation is shared with the world**
* [ ] Develop a new "All features" index in **Reference**
* [ ] Main index page sub-section refinements
  * Explanation
  * How-to Guides
  * Reference
  * Features removed or replaced (TBD)

### Remove

* [ ] Any existing empty levels or old articles are removed or modified to an acceptable quality and Diátaxis alignment. This should not be the case.

**Comment by ericholscher** [comment]
I think we're not tracking this work anymore and it's gone stale. Going to close the tracking issues.
